export const DUMMY_RACKS = [
  {
    _id: "RK01",
    rackNumber: "RACK-01",
    location: "Freezer Line",
    area: "Part Process",
    capacity: "5000 kg",
    shelves: [
      {
        _id: "SL01",
        rackId: "RK01",
        shelfNumber: "S1",
        items: [
          {
            _id: "IT01",
            sapCode: "SAP12345",
            itemName: "Compressor",
            description: "High-pressure refrigeration compressor",
            quantity: 1200,
            rackId: "RK01",
            shelfId: "SL01",
            lastUpdated: "2025-12-26T12:30:00Z",
          },
          {
            _id: "IT02",
            sapCode: "SAP12346",
            itemName: "Condenser Coil",
            description: "Copper condenser coil for cooling units",
            quantity: 850,
            rackId: "RK01",
            shelfId: "SL01",
            lastUpdated: "2025-12-25T09:15:00Z",
          },
        ],
      },
      {
        _id: "SL02",
        rackId: "RK01",
        shelfNumber: "S2",
        items: [
          {
            _id: "IT03",
            sapCode: "SAP12347",
            itemName: "Evaporator Fan",
            description: "Axial fan for evaporator airflow",
            quantity: 640,
            rackId: "RK01",
            shelfId: "SL02",
            lastUpdated: "2025-12-24T16:45:00Z",
          },
          {
            _id: "IT04",
            sapCode: "SAP12348",
            itemName: "Expansion Valve",
            description: "Thermostatic expansion valve",
            quantity: 420,
            rackId: "RK01",
            shelfId: "SL02",
            lastUpdated: "2025-12-23T11:10:00Z",
          },
        ],
      },
      {
        _id: "SL03",
        rackId: "RK01",
        shelfNumber: "S3",
        items: [
          {
            _id: "IT05",
            sapCode: "SAP12349",
            itemName: "Refrigerant Filter Drier",
            description: "Moisture removal filter for refrigeration systems",
            quantity: 300,
            rackId: "RK01",
            shelfId: "SL03",
            lastUpdated: "2025-12-22T08:00:00Z",
          },
        ],
      },
    ],
  },
];
